language: java
env:
  global:
  - SONATYPE_USERNAME=vpro
  - secure: n94Ya4C4DIJLqYY0K+/41kCO4gbVA2+FmYIXVYQaHPtYI0rJhEMRp2pRMXEIFnl4bksEpkDdNZ15FbPVEKzQDNVKxKudXrL1bEZQzUDT42c6iSPbDtSpoNcTkhwqhlIjImHqGJjuxafmWxSEqMnCXGOcWxj8w1urd6zNcBd6URkjhV9xFN7vNcOqjssHd+BXUJYKQ9NEi8a13/nkPJRsxOqLwUAFgmiBBGOZhzBP0TDi7m3L1+AzQXMN8hnBuILhWeB8XUtxt1jEYbTgFCl28GxYLFRq1hETctE2Bmy6Si6warKIXfplOWPr0Y+MM/TCbfRaFCddeaaU5hj8JkSMFPBvZ7kGG7hLh+C71cz9pRPJqgL01HKbfRc/LfeVL0AShpSdFGBO/2EbsQcGrRURTzJYzUlQJZb0du6RQM9gHlCEklg3Va2sHC6IUztuZb46RxcU2ynkTzuSEtAZGULZtXrBxzJlN6ALqeJAxn5X8y9Wl4h+l8GVezaVmkFuBiVX1S/sn5wakvOUTJRX+19uChT6UrMciN253LiPNByLGasF3Se9Ee1uzfPskuTyvcs5kMC95xRWoN9wY4odz8ZIEb2gIM4yjr91ZQ9ndYar3ecY9/muzpLlAF2bmv7g4pa6SfwkEuYzyX6tLfAh/g9J8hIhy7fCm9hUwlMbrzvbblQ=
jdk:
- openjdk8
sudo: false
script: mvn clean test install
after_success:
- mvn -Pdeploy,ossrh deploy --settings .travis-settings.xml -DskipTests=true -Dgpg.skip=true  -B
- bash <(curl -s https://codecov.io/bash)
